### ISSUE TITLE
move

### ISSUE THREAD

**Issue by sonnyp** [lloydwatkin/node-stringprep-icu#2]
@lloydwatkin :wave: 

node-stringprep and node-expat are moving back to astro account as node-xmpp doesn't use them any more

Could you move node-stringprep-icu to your repo as well? For the same reason.

**Comment by lloydwatkin** [comment]
I think we can just kill `node-stringprep-icu` ?

Guessing @astro will need to move `node-stringprep` and `node-expat` ?

**Comment by sonnyp** [comment]
> Guessing @astro will need to move node-stringprep and node-expat ?

Yes he will look at it tonight.

> I think we can just kill node-stringprep-icu ?

Fine by me, should I remove the repository?

**Comment by lloydwatkin** [comment]
I'll sort the other repo tomorrow. Thanks!

**Comment by lloydwatkin** [comment]
In the end I just moved since I can't unpublish from npm, so it seems safer.

---

Steven Lloyd Watkin
Software Engineer
PHP ::: Java ::: Ruby ::: Node.js ::: JavaScript ::: XMPP :: + many more
lloyd@evilprofessor.co.uk (email+jid) ::: http://www.evilprofessor.co.uk
Github / Twitter / Flickr / Facebook: lloydwatkin

Organiser of WORLD RECORD breaking charity event:
Scuba Santas ::: http://www.scuba-santas.co.uk
Supporting the RNLI & DDRC - NDAC, Chepstow

**Comment by sonnyp** [comment]
thx
